FROM hashicorp/terraform:1.8

RUN apk add --no-cache bash curl; \
    # Install tflint
    curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash; \
    # Install terraform-docs
    curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz; \
    tar -xzf terraform-docs.tar.gz; \
    chmod +x terraform-docs; \
    mv terraform-docs /usr/local/bin/terraform-docs; \
    rm terraform-docs.tar.gz

RUN mkdir /work

WORKDIR /work

ENTRYPOINT [ "/bin/bash" ]
